/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 21
#define LARGE_STATE_COUNT 18
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  sym_comment = 7,
  sym_string = 8,
  sym_number = 9,
  sym_boolean = 10,
  sym_null = 11,
  sym_undefined = 12,
  anon_sym_DOLLAR = 13,
  anon_sym_BSLASH = 14,
  sym_symbol = 15,
  sym_source_file = 16,
  sym__expr = 17,
  sym_list = 18,
  sym_vector = 19,
  sym_map = 20,
  sym_expand = 21,
  sym_quote = 22,
  aux_sym_source_file_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_comment] = "comment",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [sym_null] = "null",
  [sym_undefined] = "undefined",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_BSLASH] = "\\",
  [sym_symbol] = "symbol",
  [sym_source_file] = "source_file",
  [sym__expr] = "_expr",
  [sym_list] = "list",
  [sym_vector] = "vector",
  [sym_map] = "map",
  [sym_expand] = "expand",
  [sym_quote] = "quote",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_comment] = sym_comment,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [sym_null] = sym_null,
  [sym_undefined] = sym_undefined,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [sym_symbol] = sym_symbol,
  [sym_source_file] = sym_source_file,
  [sym__expr] = sym__expr,
  [sym_list] = sym_list,
  [sym_vector] = sym_vector,
  [sym_map] = sym_map,
  [sym_expand] = sym_expand,
  [sym_quote] = sym_quote,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_undefined] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_expand] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {'!', '!'}, {'*', '+'}, {'-', '-'}, {'/', '/'}, {'<', '?'}, {'A', 'Z'}, {'_', '_'}, {'a', 'z'},
  {'~', '~'},
};

static const TSCharacterRange sym_symbol_character_set_2[] = {
  {'!', '!'}, {'*', '+'}, {'-', '-'}, {'/', '9'}, {'<', '?'}, {'A', 'Z'}, {'_', '_'}, {'a', 'z'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 1,
        '#', 13,
        '$', 21,
        '(', 7,
        ')', 8,
        '-', 40,
        '[', 9,
        '\\', 22,
        ']', 10,
        'f', 23,
        'n', 39,
        't', 36,
        'u', 34,
        '{', 11,
        '}', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '-') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (set_contains(sym_symbol_character_set_1, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_boolean);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_null);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_undefined);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'a') ADVANCE(31);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'd') ADVANCE(20);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'd') ADVANCE(27);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'e') ADVANCE(18);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'e') ADVANCE(29);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'e') ADVANCE(24);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'f') ADVANCE(30);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'i') ADVANCE(35);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'l') ADVANCE(37);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'l') ADVANCE(19);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'l') ADVANCE(32);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'n') ADVANCE(25);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'n') ADVANCE(28);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'r') ADVANCE(38);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 's') ADVANCE(26);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'u') ADVANCE(26);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'u') ADVANCE(33);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_symbol);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(41);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_undefined] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym__expr] = STATE(6),
    [sym_list] = STATE(6),
    [sym_vector] = STATE(6),
    [sym_map] = STATE(6),
    [sym_expand] = STATE(6),
    [sym_quote] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_boolean] = ACTIONS(15),
    [sym_null] = ACTIONS(15),
    [sym_undefined] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [sym_symbol] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__expr] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_map] = STATE(2),
    [sym_expand] = STATE(2),
    [sym_quote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(26),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(32),
    [sym_number] = ACTIONS(35),
    [sym_boolean] = ACTIONS(35),
    [sym_null] = ACTIONS(35),
    [sym_undefined] = ACTIONS(35),
    [anon_sym_DOLLAR] = ACTIONS(38),
    [anon_sym_BSLASH] = ACTIONS(41),
    [sym_symbol] = ACTIONS(35),
  },
  [STATE(3)] = {
    [sym__expr] = STATE(7),
    [sym_list] = STATE(7),
    [sym_vector] = STATE(7),
    [sym_map] = STATE(7),
    [sym_expand] = STATE(7),
    [sym_quote] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(44),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(46),
    [sym_number] = ACTIONS(48),
    [sym_boolean] = ACTIONS(48),
    [sym_null] = ACTIONS(48),
    [sym_undefined] = ACTIONS(48),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [sym_symbol] = ACTIONS(48),
  },
  [STATE(4)] = {
    [sym__expr] = STATE(8),
    [sym_list] = STATE(8),
    [sym_vector] = STATE(8),
    [sym_map] = STATE(8),
    [sym_expand] = STATE(8),
    [sym_quote] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(52),
    [sym_number] = ACTIONS(54),
    [sym_boolean] = ACTIONS(54),
    [sym_null] = ACTIONS(54),
    [sym_undefined] = ACTIONS(54),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [sym_symbol] = ACTIONS(54),
  },
  [STATE(5)] = {
    [sym__expr] = STATE(9),
    [sym_list] = STATE(9),
    [sym_vector] = STATE(9),
    [sym_map] = STATE(9),
    [sym_expand] = STATE(9),
    [sym_quote] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(56),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(58),
    [sym_number] = ACTIONS(60),
    [sym_boolean] = ACTIONS(60),
    [sym_null] = ACTIONS(60),
    [sym_undefined] = ACTIONS(60),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [sym_symbol] = ACTIONS(60),
  },
  [STATE(6)] = {
    [sym__expr] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_map] = STATE(2),
    [sym_expand] = STATE(2),
    [sym_quote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(62),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(64),
    [sym_number] = ACTIONS(66),
    [sym_boolean] = ACTIONS(66),
    [sym_null] = ACTIONS(66),
    [sym_undefined] = ACTIONS(66),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [sym_symbol] = ACTIONS(66),
  },
  [STATE(7)] = {
    [sym__expr] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_map] = STATE(2),
    [sym_expand] = STATE(2),
    [sym_quote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(68),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(64),
    [sym_number] = ACTIONS(66),
    [sym_boolean] = ACTIONS(66),
    [sym_null] = ACTIONS(66),
    [sym_undefined] = ACTIONS(66),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [sym_symbol] = ACTIONS(66),
  },
  [STATE(8)] = {
    [sym__expr] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_map] = STATE(2),
    [sym_expand] = STATE(2),
    [sym_quote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(70),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(64),
    [sym_number] = ACTIONS(66),
    [sym_boolean] = ACTIONS(66),
    [sym_null] = ACTIONS(66),
    [sym_undefined] = ACTIONS(66),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [sym_symbol] = ACTIONS(66),
  },
  [STATE(9)] = {
    [sym__expr] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_map] = STATE(2),
    [sym_expand] = STATE(2),
    [sym_quote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(72),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(64),
    [sym_number] = ACTIONS(66),
    [sym_boolean] = ACTIONS(66),
    [sym_null] = ACTIONS(66),
    [sym_undefined] = ACTIONS(66),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [sym_symbol] = ACTIONS(66),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(74),
    [anon_sym_RPAREN] = ACTIONS(74),
    [anon_sym_LBRACK] = ACTIONS(74),
    [anon_sym_RBRACK] = ACTIONS(74),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_RBRACE] = ACTIONS(74),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(74),
    [sym_number] = ACTIONS(76),
    [sym_boolean] = ACTIONS(76),
    [sym_null] = ACTIONS(76),
    [sym_undefined] = ACTIONS(76),
    [anon_sym_DOLLAR] = ACTIONS(74),
    [anon_sym_BSLASH] = ACTIONS(74),
    [sym_symbol] = ACTIONS(76),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(78),
    [anon_sym_LPAREN] = ACTIONS(78),
    [anon_sym_RPAREN] = ACTIONS(78),
    [anon_sym_LBRACK] = ACTIONS(78),
    [anon_sym_RBRACK] = ACTIONS(78),
    [anon_sym_LBRACE] = ACTIONS(78),
    [anon_sym_RBRACE] = ACTIONS(78),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(78),
    [sym_number] = ACTIONS(80),
    [sym_boolean] = ACTIONS(80),
    [sym_null] = ACTIONS(80),
    [sym_undefined] = ACTIONS(80),
    [anon_sym_DOLLAR] = ACTIONS(78),
    [anon_sym_BSLASH] = ACTIONS(78),
    [sym_symbol] = ACTIONS(80),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(82),
    [anon_sym_LPAREN] = ACTIONS(82),
    [anon_sym_RPAREN] = ACTIONS(82),
    [anon_sym_LBRACK] = ACTIONS(82),
    [anon_sym_RBRACK] = ACTIONS(82),
    [anon_sym_LBRACE] = ACTIONS(82),
    [anon_sym_RBRACE] = ACTIONS(82),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(82),
    [sym_number] = ACTIONS(84),
    [sym_boolean] = ACTIONS(84),
    [sym_null] = ACTIONS(84),
    [sym_undefined] = ACTIONS(84),
    [anon_sym_DOLLAR] = ACTIONS(82),
    [anon_sym_BSLASH] = ACTIONS(82),
    [sym_symbol] = ACTIONS(84),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(86),
    [anon_sym_LPAREN] = ACTIONS(86),
    [anon_sym_RPAREN] = ACTIONS(86),
    [anon_sym_LBRACK] = ACTIONS(86),
    [anon_sym_RBRACK] = ACTIONS(86),
    [anon_sym_LBRACE] = ACTIONS(86),
    [anon_sym_RBRACE] = ACTIONS(86),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(86),
    [sym_number] = ACTIONS(88),
    [sym_boolean] = ACTIONS(88),
    [sym_null] = ACTIONS(88),
    [sym_undefined] = ACTIONS(88),
    [anon_sym_DOLLAR] = ACTIONS(86),
    [anon_sym_BSLASH] = ACTIONS(86),
    [sym_symbol] = ACTIONS(88),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(90),
    [anon_sym_LPAREN] = ACTIONS(90),
    [anon_sym_RPAREN] = ACTIONS(90),
    [anon_sym_LBRACK] = ACTIONS(90),
    [anon_sym_RBRACK] = ACTIONS(90),
    [anon_sym_LBRACE] = ACTIONS(90),
    [anon_sym_RBRACE] = ACTIONS(90),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(90),
    [sym_number] = ACTIONS(92),
    [sym_boolean] = ACTIONS(92),
    [sym_null] = ACTIONS(92),
    [sym_undefined] = ACTIONS(92),
    [anon_sym_DOLLAR] = ACTIONS(90),
    [anon_sym_BSLASH] = ACTIONS(90),
    [sym_symbol] = ACTIONS(92),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(94),
    [anon_sym_LPAREN] = ACTIONS(94),
    [anon_sym_RPAREN] = ACTIONS(94),
    [anon_sym_LBRACK] = ACTIONS(94),
    [anon_sym_RBRACK] = ACTIONS(94),
    [anon_sym_LBRACE] = ACTIONS(94),
    [anon_sym_RBRACE] = ACTIONS(94),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(94),
    [sym_number] = ACTIONS(96),
    [sym_boolean] = ACTIONS(96),
    [sym_null] = ACTIONS(96),
    [sym_undefined] = ACTIONS(96),
    [anon_sym_DOLLAR] = ACTIONS(94),
    [anon_sym_BSLASH] = ACTIONS(94),
    [sym_symbol] = ACTIONS(96),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(98),
    [anon_sym_LPAREN] = ACTIONS(98),
    [anon_sym_RPAREN] = ACTIONS(98),
    [anon_sym_LBRACK] = ACTIONS(98),
    [anon_sym_RBRACK] = ACTIONS(98),
    [anon_sym_LBRACE] = ACTIONS(98),
    [anon_sym_RBRACE] = ACTIONS(98),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(98),
    [sym_number] = ACTIONS(100),
    [sym_boolean] = ACTIONS(100),
    [sym_null] = ACTIONS(100),
    [sym_undefined] = ACTIONS(100),
    [anon_sym_DOLLAR] = ACTIONS(98),
    [anon_sym_BSLASH] = ACTIONS(98),
    [sym_symbol] = ACTIONS(100),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(102),
    [anon_sym_RPAREN] = ACTIONS(102),
    [anon_sym_LBRACK] = ACTIONS(102),
    [anon_sym_RBRACK] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(102),
    [anon_sym_RBRACE] = ACTIONS(102),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(102),
    [sym_number] = ACTIONS(104),
    [sym_boolean] = ACTIONS(104),
    [sym_null] = ACTIONS(104),
    [sym_undefined] = ACTIONS(104),
    [anon_sym_DOLLAR] = ACTIONS(102),
    [anon_sym_BSLASH] = ACTIONS(102),
    [sym_symbol] = ACTIONS(104),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 2,
      sym_number,
      sym_symbol,
  [8] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      sym_symbol,
  [15] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(18)] = 0,
  [SMALL_STATE(19)] = 8,
  [SMALL_STATE(20)] = 15,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expand, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expand, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [110] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_anascript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "anascript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
